[STATE]

;last opened map file
last_map = D:\Hry\SPELCROS\MOD\Spellcross-Mod-CZ-Hard\mod\data\HARD_MISSIONS\M04_03A.DEF

;last export data path
export_path = F:\Data\3d\smrky

;default MIDI file to play on startup
default_midi = M_MUS04

;volumes {0 to 100}
sound_volume = 8
music_volume = 18

;default window size
win_x_size = 1600
win_y_size = 1200
win_maximize = true

;hide missing resources warnings when loading maps
hide_map_load_warnings = true

;gamma correction
gamme = 1.400000
extract_fs_path = D:\Hry\spelcros_temp\DATA

; last trees randomizer presets
tree_randomizer_preset<1> = F:\Data\C\_msvc_\spellcross-map-edit\builds\x64\Debug\data\tree_randomizer\presets\trees_randomizer_preset.info


[SPELCROS]

;spellcross installation data folder
spell_path = D:\hry\SPELLCROSS\DATA
spell_path<1> = D:\Hry\spelcros_temp\DATA
spell_path<2> = D:\Hry\spelcros_temp
spell_path<3> = D:\Hry\SPELCROS\DATA
spell_path<4> = 
spell_path<5> = 
spell_path<6> = 
spell_path<7> = 
spell_path<8> = 
spell_path<9> = 

;spellcross CD copy data path
spellcd_path = 
spellcd_path<1> = D:\Hry\spellcd_temp\DATA
spellcd_path<2> = D:\Hry\spellcd_temp
spellcd_path<3> = D:\Hry\spellcd\DATA
spellcd_path<4> = 
spellcd_path<5> = 
spellcd_path<6> = 
spellcd_path<7> = 
spellcd_path<8> = 
spellcd_path<9> = 

; spellcross mod path (optional)
mod_path = D:\Hry\SPELCROS\MOD\Spellcross-Mod-CZ-Hard\mod\make
mod_path<1> = D:\Hry\SPELCROS\MOD\test_cz\make
mod_path<2> = D:\Hry\SPELCROS\MOD\mod_units\make
mod_path<3> = 
mod_path<4> = 
mod_path<5> = 
mod_path<6> = 
mod_path<7> = 
mod_path<8> = 
mod_path<9> = 


[DATA]

;additional program data folder
spec_data_path = data\

;some additional metadata for units.fsu
units_aux_data_path = data\units.fsa

;trees randomzier classes relative directory
tree_randomizer_classes_dir = data/tree_randomizer


[TERRAIN::T11]
context_path = data\T11.con


[TERRAIN::PUST]
context_path = data\PUST.con


[TERRAIN::DEVAST]
context_path = data\DEVAST.con
