[STATE]

;last opened map file
last_map = D:\Hry\SPELCROS\DATA\data\COMMON\M01_01A.DEF

;last export data path
export_path = 

;default MIDI file to play on startup
default_midi = M_MUS04

;volumes {0 to 100}
sound_volume = 50
music_volume = 50

;default window size
win_x_size = 1600
win_y_size = 1200
win_maximize = true

;hide missing resources warnings when loading maps
hide_map_load_warnings = true


[SPELCROS]

;spellcross installation data folder
spell_path = D:\hry\SPELLCROSS\DATA
spell_path<1> = 
spell_path<2> = 
spell_path<3> = 
spell_path<4> = 
spell_path<5> = 
spell_path<6> = 
spell_path<7> = 
spell_path<8> = 
spell_path<9> = 

;spellcross CD copy data path
spellcd_path = D:\hry\SPELLCROSS\DATA
spellcd_path<1> = 
spellcd_path<2> = 
spellcd_path<3> = 
spellcd_path<4> = 
spellcd_path<5> = 
spellcd_path<6> = 
spellcd_path<7> = 
spellcd_path<8> = 
spellcd_path<9> = 

; spellcross mod path (optional)
mod_path = 
mod_path<1> = 
mod_path<2> = 
mod_path<3> = 
mod_path<4> = 
mod_path<5> = 
mod_path<6> = 
mod_path<7> = 
mod_path<8> = 
mod_path<9> = 


[DATA]

;additional program data folder
spec_data_path = data\

;some additional metadata for units.fsu
units_aux_data_path = data\units.fsa


[TERRAIN::T11]
context_path = data\T11.con


[TERRAIN::PUST]
context_path = data\PUST.con


[TERRAIN::DEVAST]
context_path = data\DEVAST.con
