//=============================================================================
// Spellcross color palette related stuff.
// 
// This code is part of Spellcross Map Editor project.
// (c) 2021-2026, Stanislav Maslan, s.maslan@seznam.cz
// Distributed under MIT license, https://opensource.org/licenses/MIT.
//=============================================================================
#include "spell_palette.h"
//#include "sprites.h"
//#include "fs_archive.h"
//#include "fsu_archive.h"
//#include "spell_units.h"
//#include "LZ_spell.h"
//#include "spell_texts.h"
#include "other.h"
//#include "map.h"

#include <fstream>
#include <string>
#include <vector>
#include <stdexcept>
#include <regex>
#include <filesystem>

#include <wx/rawbmp.h>


//=============================================================================
// Spellcross palette
//=============================================================================

// make palette record
SpellPalette::SpellPalette()
{
	m_name = "empty";
	m_pal.assign(3*256,0);
	m_used.assign(256,0);
}

// make palette record
SpellPalette::SpellPalette(std::string name)
{
	m_name = name;
	m_pal.assign(3*256,0);
	m_used.assign(256,0);
}

// clear palette colors
void SpellPalette::Clear()
{
	m_pal.assign(3*256,0);
	m_used.assign(256,0);
	m_name = "";
	m_chunks.clear();
}

// place chunk of data to palette with offset (0 - 255)
int SpellPalette::Insert(std::vector<uint8_t>& data,std::string name,int offset,int count)
{
	if(!count)
		count = data.size()/3;
	if(3*count > data.size())
		return(1);
	if(count && offset + count > 256)
		return(1);
	
	memcpy(m_pal.data() + offset*3,data.data(),count*3);
	memset(m_used.data() + offset,1,count);
	
	// add chunk record
	SpellPalette::Chunk chunk;
	chunk.name = name;
	chunk.offset = offset;
	chunk.size = count;
	m_chunks.push_back(chunk);
		
	return(0);
}

// place chunk of data to palette from file with offset (0 - 255)
int SpellPalette::Insert(std::wstring path,int offset,std::string used)
{
	ifstreamext fr(path.c_str(),std::ios::in);
	if(!fr.is_open())
		return(1);
	auto chunk = fr.read_vector();
	fr.close();
	auto name = std::filesystem::path(path).filename().string();
	if(Insert(chunk,name,offset))
		return(1);
	
	// try assign mask of used colors from string style: 0, 128-191, ...
	if(used.empty())
		return(1);
	m_used.assign(256,0);

	// parse used string
	std::regex regexz(",");
	auto chunks = std::vector<std::string>(std::sregex_token_iterator(used.begin(),used.end(),regexz,-1),std::sregex_token_iterator());
	for(auto &chunk: chunks)
	{
		auto list = regexp_get(chunk,"\\s*([\\d]+)\\s*-*\\s*([\\d]+)*");
		if(list.size() < 1)
			return(1);
		int from = std::atoi(list[0].c_str());
		int to = -1;
		if(list.size() >= 2 && !list[1].empty())
			to = std::atoi(list[1].c_str());
		if(from > 255 || to > 255)
			return(1);		
		m_used[from] = 1;
		if(to > 0)
			std::fill(m_used.begin() + from, m_used.begin() + to, 1);
	}
	return(0);
}

// get assigned range
std::tuple<int,int> SpellPalette::GetRange(int start)
{
	auto beg = std::find(m_used.begin() + start, m_used.end(), 1);
	if(beg == m_used.end())
		return std::tuple(-1,-1);
	auto end = std::find(beg,m_used.end(),0);
	if(end == m_used.end())
		end = m_used.end();	
	return std::tuple(beg - m_used.begin(),end - m_used.begin() - 1);
}

// get assigned range string
std::string SpellPalette::GetRangeString()
{
	int offset = 0;
	bool was0 = false;
	std::string palstr = "";
	while(true)
	{
		auto [p1,p2] = GetRange(offset);
		if(p1 < 0 || p2 < 0)
			break;
		if(p1 == 0)
			was0 = true;
		if(offset)
			palstr += ", ";
		palstr += string_format("%d-%d",p1,p2);
		offset = p2 + 1;
	}
	if(!was0)
	palstr = "0, " + palstr;
	return(palstr);
}

// save palette to file
int SpellPalette::Save(std::wstring path)
{
	// try open file
	ofstreamext fw(path,std::ios::out | std::ios::binary | std::ios::trunc);
	if(!fw.is_open())
		return(1);

	fw.write((const char*)m_pal.data(),m_pal.size());
	fw.close();

	return(0);
}

// save palette chunks to file
int SpellPalette::SaveChunks(std::wstring directory_path)
{
	// for each palette chunk:
	for(auto &chunk: m_chunks)
	{
		if(chunk.offset + chunk.size > m_pal.size()/3)
			return(1);

		// try make file
		auto path = std::filesystem::path(directory_path).append(chunk.name).wstring();
		ofstreamext fw(path,std::ios::out | std::ios::binary | std::ios::trunc);
		if(!fw.is_open())
			return(1);
				
		// store chunk
		fw.write((const char*)m_pal.data() + chunk.offset*3,chunk.size*3);
		fw.close();
	}

	return(0);
}



// save palette as info file
int SpellPalette::SaveInfo(std::filesystem::path path)
{
	std::string info = "";

	info += string_format("// Spellcross palette meta file (autogenerated by Spellcross Map Editor)\n");
	info += string_format("name:: %s\n",m_name.c_str());
	info += string_format("size:: %d\n",m_pal.size()/3);
	info += string_format("assigned:: %s\n",GetRangeString().c_str());

	std::vector<std::string> list;
	for(int k = 0; k < m_pal.size() - 2; k += 3)
		list.push_back(string_format("%3u, %3u, %3u",m_pal[k + 0],m_pal[k + 1],m_pal[k + 2]));
	info += string_format("\n");
	info += info_make_text_vector("colors",list,"// format: R, G, B");

	std::vector<std::string> chunk_names;
	for(auto &chunk: m_chunks)
		chunk_names.push_back(chunk.name);	
	info += string_format("\n");
	info += info_make_text_vector("chunks list",chunk_names);
			
	for(auto& chunk: m_chunks)
	{
		std::string cinf = "";
		
		cinf += string_format("offset:: %d\n",chunk.offset);
		cinf += string_format("size:: %d\n\n",chunk.size);
		
		std::vector<std::string> list;
		for(int k = chunk.offset; k < chunk.offset + chunk.size; k += 3)
			list.push_back(string_format("%3u, %3u, %3u",m_pal[k + 0],m_pal[k + 1],m_pal[k + 2]));
		cinf += info_make_text_vector("colors",list,"// format: R, G, B");

		info += string_format("\n");
		info += info_make_section(chunk.name,cinf);
	}
	
	// save file only if differs from existing
	std::string info_old;
	loadstr(path,info_old);
	if(info_old == info)
		return(0);
	return(savestr(path,info));
}

// load palette from info file
int SpellPalette::LoadInfo(std::filesystem::path path)
{
	Clear();

	// load source info
	std::string infostr;
	if(loadstr(path,infostr))
		return(1);
	auto info = get_text_lines(infostr);

	// palette name
	m_name = info_get_string(info, "name");
	if(m_name.empty())
		return(1);
	
	// read common colors list
	auto colors_list = info_get_text_vector(info,"colors");
	int cid = 0;
	for(auto &color: colors_list)
	{
		int r,g,b;
		if(cid >= 3*256 || std::sscanf(color.c_str(),"%d,%d,%d",&r,&g,&b) != 3)
		{
			Clear();
			return(1);
		}
		m_pal[cid + 0] = r;
		m_pal[cid + 1] = g;
		m_pal[cid + 2] = b;
		cid += 3;		
	}

	// parse assigned string
	auto assigned = info_get_string(info,"assigned");
	if(assigned.empty())
	{
		Clear();
		return(1);
	}
	auto chunks = get_text_lines(assigned, true, ',');
	for(auto& chunk: chunks)
	{
		auto list = regexp_get(chunk,"\\s*([\\d]+)\\s*-*\\s*([\\d]+)*");
		if(list.size() < 1)
		{
			Clear();
			return(1);
		}
		int from = std::atoi(list[0].c_str());
		int to = -1;
		if(list.size() >= 2 && !list[1].empty())
			to = std::atoi(list[1].c_str());
		if(from > 255 || to > 255)
		{
			Clear();
			return(1);
		}
		m_used[from] = 1;
		if(to > 0)
			std::fill(m_used.begin() + from,m_used.begin() + to,1);
	}

	// parse chunks
	auto chunk_list = info_get_text_vector(info, "chunks list");
	for(auto &chunk_name: chunk_list)
	{
		auto cinf = info_get_section(info,chunk_name);
		Chunk chunk;
		chunk.name = chunk_name;
		chunk.offset = info_get_int(cinf,"offset",-1);
		chunk.size = info_get_int(cinf,"size",-1);
		if(chunk.size < 0 || chunk.offset < 0 || chunk.offset + chunk.size > 256)
		{
			Clear();
			return(1);
		}
		m_chunks.push_back(chunk);
	}

	return(0);
}


// render palette into bitmap (scale up as much as possible)
int SpellPalette::Render(wxBitmap& bmp)
{
	// canvas size
	int surf_x = bmp.GetWidth();
	int surf_y = bmp.GetHeight();

	int x_color_width = surf_x/256;
	int x_ofs = (surf_x - x_color_width*256)/2;
	int x_end = x_ofs + x_color_width*256;

	// split vertically
	int filter_y_limit = surf_y/2;

	// palette
	uint8_t (*pal)[3] = (uint8_t(*)[3])m_pal.data();

	// render 24bit RGB data to raw bmp buffer
	wxNativePixelData data(bmp);
	wxNativePixelData::Iterator p(data);
	for(int y = 0; y < surf_y; ++y)
	{
		uint8_t* scan = p.m_ptr;
		for(int x = 0; x < surf_x; x++)
		{
			if(x < 1 || x >= surf_x-1 || y < 1 || y >= surf_y-1)
			{
				*scan++ = 0x00;
				*scan++ = 0x00;
				*scan++ = 0x00;
			}
			else if(x >= x_ofs && x < x_end)
			{
				int color = (x - x_ofs)/x_color_width;
				*scan++ = pal[color][2];
				*scan++ = pal[color][1];
				*scan++ = pal[color][0];
			}
			else
			{
				uint8_t color = (!(x&32) ^ !(y&32))?0x88:0xAA;
				*scan++ = color;
				*scan++ = color;
				*scan++ = color;
			}
		}
		p.OffsetY(data,1);
	}

	return(0);
}

// render palette color selection into canvas
int SpellPalette::RenderPaletteColor(wxBitmap& bmp,int x_size,int x_pos,uint8_t* filter)
{
	// canvas size
	int surf_x = bmp.GetWidth();
	int surf_y = bmp.GetHeight();

	// palette position and size in canvas
	int x_color_width = x_size/256;
	int x_ofs = (x_size - x_color_width*256)/2;
	int x_end = x_ofs + x_color_width*256;

	int is_selected = x_pos >= x_ofs && x_pos < x_end;
	int pal_id = (is_selected)?((x_pos - x_ofs)/x_color_width):-1;
	if(filter)
		pal_id = filter[pal_id];

	uint8_t(*pal)[3] = (uint8_t(*)[3])m_pal.data();

	// render 24bit RGB data to raw bmp buffer
	wxNativePixelData data(bmp);
	wxNativePixelData::Iterator p(data);
	for(int y = 0; y < surf_y; ++y)
	{
		uint8_t* scan = p.m_ptr;
		for(int x = 0; x < surf_x; x++)
		{
			if(x > 0 && x < surf_x-1 && y > 0 && y < surf_y-1)
			{
				if(is_selected)
				{
					*scan++ = pal[pal_id][2];
					*scan++ = pal[pal_id][1];
					*scan++ = pal[pal_id][0];
				}
				else
				{
					uint8_t color = (!(x&8) ^ !(y&8))?0x88:0xAA;
					*scan++ = color;
					*scan++ = color;
					*scan++ = color;
				}
			}
			else
			{
				*scan++ = 0x00;
				*scan++ = 0x00;
				*scan++ = 0x00;
			}
		}
		p.OffsetY(data,1);
	}

	return(pal_id);
}




